### ISSUE TITLE
Can't build zwave4j with gradle 1.6

### ISSUE THREAD

**Issue by jrushford** [zgmnkv/zwave4j#25]
I saw another issue that says zwave4j should build with gradle 1.6 but this is not the case.  I get the following errors:
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jjr/zwave4j/build.gradle' line: 69

* What went wrong:
Could not compile build file '/home/jjr/zwave4j/build.gradle'.
> startup failed:
  build file '/home/jjr/zwave4j/build.gradle': 69: unable to resolve class TargetPlatformConfiguration
   @ line 69, column 72.
     TargetPlatformConfiguration() {
                                   ^

  build file '/home/jjr/zwave4j/build.gradle': 70: unable to resolve class Platform
   @ line 70, column 42.
          boolean supportsPlatform(Platform p
                                   ^

  build file '/home/jjr/zwave4j/build.gradle': 83: unable to resolve class TargetPlatformConfiguration
   @ line 83, column 72.
     TargetPlatformConfiguration() {
                                   ^

  build file '/home/jjr/zwave4j/build.gradle': 84: unable to resolve class Platform
   @ line 84, column 42.
          boolean supportsPlatform(Platform p
                                   ^

  4 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 33.176 secs
jjr@cubietruck:~/zwave4j$ gradle --version

------------------------------------------------------------
Gradle 1.6
------------------------------------------------------------

Gradle build time: Tuesday, May 7, 2013 9:12:14 AM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.8.4 compiled on May 22 2012
Ivy: 2.2.0
JVM: 1.7.0_65 (Oracle Corporation 24.65-b04)
OS: Linux 3.4.79 arm

**Comment by zgmnkv** [comment]
Gradle 1.6 is not supported.
Use gradle 1.12, or gradle wrapper included in project.

**Comment by jrushf1239k** [comment]
Thanks,

I used the gradlew wrapper but, now I get link errors.  I have openzwave 1.2.919 built and installed.  I pointed my gradle.properties at the openzwave-1.2.919 src directory and config directory.

Here are the errors:

Unzipping /home/jjr/.gradle/wrapper/dists/gradle-1.12-bin/2qvnajdoo11hasdfkikjaci26k/gradle-1.12-bin.zip to /home/jjr/.gradle/wrapper/dists/gradle-1.12-bin/2qvnajdoo11hasdfkikjaci26k
Set executable permissions for: /home/jjr/.gradle/wrapper/dists/gradle-1.12-bin/2qvnajdoo11hasdfkikjaci26k/gradle-1.12/bin/gradle
:configZip
:compileJava
:processResources UP-TO-DATE
:classes
:mainCExtractHeaders
:compileLinux_armMainSharedLibraryMainC
:generateNativeHeaders
:generateOzwVersionCpp
:mainCppExtractHeaders
:compileLinux_armMainSharedLibraryMainCpp
:linkLinux_armMainSharedLibrary/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/692uc2246m4h5l02upd7japig/version.o:(.data+0x0): multiple definition of `ozw_vers_minor'
/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/1mu1lpe17h2q2rpon1npt20kgm/vers.o:(.data+0x2): first defined here
/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/692uc2246m4h5l02upd7japig/version.o:(.bss+0x0): multiple definition of `ozw_vers_major'
/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/1mu1lpe17h2q2rpon1npt20kgm/vers.o:(.data+0x0): first defined here
/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/692uc2246m4h5l02upd7japig/version.o:(.bss+0x2): multiple definition of `ozw_vers_revision'
/home/jjr/zwave4j/build/objectFiles/mainSharedLibrary/linux_arm/mainCpp/1mu1lpe17h2q2rpon1npt20kgm/vers.o:(.data+0x4): first defined here
collect2: ld returned 1 exit status
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkLinux_armMainSharedLibrary'.
> Linker failed; see the error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7 mins 41.072 secs

**Comment by zgmnkv** [comment]
Try Open-ZWave revision 801, newer revisions may have incompatibilities

**Comment by m0rphi** [comment]
Hi, 
I had exactly the same error like jrushf1239k with openzwave 1.2.919. 
I tried open-zwave revision 801 (for those who dont know how to find: http://code.google.com/p/open-zwave/source/checkout ) but I have other error right now:
Mehrfachdefinition is in english multiple definition, if there is some kind of confusion ;)
Thanks in advance for your help!

```
./gradlew run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:mainCExtractHeaders UP-TO-DATE
:compileLinux_amd64MainSharedLibraryMainC UP-TO-DATE
:generateNativeHeaders UP-TO-DATE
:generateOzwVersionCpp UP-TO-DATE
:mainCppExtractHeaders UP-TO-DATE
:compileLinux_amd64MainSharedLibraryMainCpp UP-TO-DATE
:linkLinux_amd64MainSharedLibrary
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o:(.bss+0x0): Mehrfachdefinition von `TiXmlString::nullrep_'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:(.bss+0x0): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `TiXmlString::append(char const*, unsigned long)':
tinystr.cpp:(.text+0x1d6): Mehrfachdefinition von `TiXmlString::append(char const*, unsigned long)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0x1d6): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o:(.rodata+0x0): Mehrfachdefinition von `TiXmlString::npos'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:(.rodata+0x0): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `TiXmlString::reserve(unsigned long)':
tinystr.cpp:(.text+0x0): Mehrfachdefinition von `TiXmlString::reserve(unsigned long)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0x0): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `TiXmlString::assign(char const*, unsigned long)':
tinystr.cpp:(.text+0xd8): Mehrfachdefinition von `TiXmlString::assign(char const*, unsigned long)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0xd8): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `operator+(TiXmlString const&, TiXmlString const&)':
tinystr.cpp:(.text+0x272): Mehrfachdefinition von `operator+(TiXmlString const&, TiXmlString const&)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0x272): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `operator+(TiXmlString const&, char const*)':
tinystr.cpp:(.text+0x30e): Mehrfachdefinition von `operator+(TiXmlString const&, char const*)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0x30e): first defined here
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7toaor6nbik4hf8eb0i5g40gi/tinystr.o: In Funktion `operator+(char const*, TiXmlString const&)':
tinystr.cpp:(.text+0x3b2): Mehrfachdefinition von `operator+(char const*, TiXmlString const&)'
/home/user/Schreibtisch/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/445e2pgt0b670i80ksa9el27h6/tinystr.o:tinystr.cpp:(.text+0x3b2): first defined here
collect2: error: ld returned 1 exit status
:linkLinux_amd64MainSharedLibrary FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkLinux_amd64MainSharedLibrary'.
> Linker failed; see the error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.727 secs

```

**Comment by zgmnkv** [comment]
I think this one is out of date, native build is completely rewritten with new version of gradle.
