### ISSUE TITLE
SIGSEGV when removing watcher from thread other than starting thread

### ISSUE THREAD

**Issue by johkin** [zgmnkv/zwave4j#26]
I've been trying to use your library from an Akka Actor, but I have run into some issues that seems connected to which thread that calls the library.
I've copied your example Main-class, but it's implemented as an actor. I start the manager from one thread and when I try to stop the manager (remove watcher, from another thread) I get the following error:

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000011f04d23c, pid=10645, tid=20483

JRE version: Java(TM) SE Runtime Environment (8.0_40-b27) (build 1.8.0_40-b27)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C  [native-lib-6986254434534746325.tmp+0x9d23c] Java_org_zwave4j_Manager_removeWatcher+0x6c

Would it be possible to alter my code and make it work? Are there some things that are bound to the thread? I can send the allOn-message without problems, also from another thread.

**Comment by gaeste** [comment]
Can only say I had the EXACT same problem.
As a side note, although not related to the problem, we are also using Akka Actors...

**Comment by Neuronix2** [comment]
This issue fixed in last commits

**Comment by mcicolella** [comment]
Hi all
I know this is a closed issue but I'm experimenting the same problem now with the last SNAPSHOT on Central Maven. The reported error when I close my plugin is
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xa1dd565c, pid=2194, tid=2635328320
#
# JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
# Java VM: Java HotSpot(TM) Client VM (25.66-b17 mixed mode linux-x86 )
# Problematic frame:
# C  [native-lib-2753289225810943132.tmp+0x10965c]  java_org_zwave4j_Manager_removeWatcher+0x87
#
Any help? Thanks
