### ISSUE TITLE
Build fails on Linux and Mac with error: Linker failed

### ISSUE THREAD

**Issue by g00dnatur3** [zgmnkv/zwave4j#27]
When i do  "sudo ./gradle build"  i get this error on Mac & Linux:

:linkLinux_amd64MainSharedLibrary
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7fkk6uubmm6ie7vlfui5c7jj74/vers.o:(.data+0x0): multiple definition of `ozw_vers_major'
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/50jbufavm6acp7s6jb61f08bp8/version.o:(.bss+0x0): first defined here
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7fkk6uubmm6ie7vlfui5c7jj74/vers.o:(.data+0x2): multiple definition of `ozw_vers_minor'
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/50jbufavm6acp7s6jb61f08bp8/version.o:(.data+0x0): first defined here
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/7fkk6uubmm6ie7vlfui5c7jj74/vers.o:(.data+0x4): multiple definition of `ozw_vers_revision'
/home/developer/zwave4j-master/build/objectFiles/mainSharedLibrary/linux_amd64/mainCpp/50jbufavm6acp7s6jb61f08bp8/version.o:(.bss+0x2): first defined here
collect2: error: ld returned 1 exit status
:linkLinux_amd64MainSharedLibrary FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkLinux_amd64MainSharedLibrary'.
> Linker failed; see the error output for details.

**Comment by g00dnatur3** [comment]
I get the same error with both openzwave-1.0.791 and openzwave-1.2.919

**Comment by Neuronix2** [comment]
Remove or comment strings in build.gradle:

//open-zwave version generated sources
srcDir "$project.buildDir/ozw-version"

**Comment by zgmnkv** [comment]
Should be fixed with #30
