### ISSUE TITLE
error on build project

### ISSUE THREAD

**Issue by apagliari1974** [zgmnkv/zwave4j#28]
When I try to build the project (0.3) for IntelliJ , Gradle give me this error:

startup failed:
  build file '/home/andrea/tmp/zwave4j-master/build.gradle': 69: unable to resolve class TargetPlatformConfiguration 
   @ line 69, column 72.
     TargetPlatformConfiguration() {

I 'use gradle 2.4 and the commeand I've used is: gradle idea
The same problem there is also when I try to build project

**Comment by Neuronix2** [comment]
Use Gradle 1.10-1.12
