### ISSUE TITLE
setNodeOn() & setNodeOff() don't do anything

### ISSUE THREAD

**Issue by ICode4Hugs** [zgmnkv/zwave4j#29]
When I run the `Main` example app as-is, all my nodes respond correctly to `switchAllOn(homeId)` and `switchAllOff(homeId)`.

However when trying to control just one node with `setNodeOn(homeId, (short)nodeId)` or `setNodeOff(homeId, (short)nodeId)` nothing happens and there is no output in the console (ConsoleOutput = true).

I've tried both binary on/off and dimmer modules.

**Comment by Neuronix2** [comment]
Perhaps the device class is defined incorrectly. Check whether the switch on-off nodes in native openzwave. I had a similar problem.

**Comment by Frechetta** [comment]
I'm having the same problem. What do you mean by the device class being defined incorrectly?

**Comment by Neuronix2** [comment]
The OZW library does not XML files, describing your device correctly. Therefore, the device does not work quite correctly.
