### ISSUE TITLE
Some manager methods that are crashing on me

### ISSUE THREAD

**Issue by PeteDub** [zgmnkv/zwave4j#31]
In an attempt to add devices to the controller while the application is running, I've found that a few MANAGER methods are causing my JRE to crash.  Basically, what I'm trying to achieve is the ability to remove the USB primary controller device while my openzwave with zwave4j application is still running, add or remove a device from the controller, then reinsert the controller and refresh the connection by destroying the manager object and creating a new one.  However, I've found that

     manager.removeWatcher(watcher, null); 

causes a JRE crash with the following message (full log can be provided if needed):

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000013249823c, pid=9807, tid=23303
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [native-lib-5094113242714591070.tmp+0x9d23c]  Java_org_zwave4j_Manager_removeWatcher+0x6c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dglogik/git/dslink-java-zwave/build/hs_err_pid9807.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

In an attempt to work around this, I commented out the removeWatcher method all together and continued with

     manager.removeDriver(controllerPort);
     manager.destroy();

followed by an attempt to create a new MANAGER object.  As such,

     manager = Manager.create();

works fine, but both

     manager.addDriver(controllerPort);
     manager.addWatcher(watcher, null);

crash the JVE as well (I've tried each independently).  The creation of the manager during startup of the application works perfectly, but reinitializing them during run time causes the crash.  Is there a way around this issue?  Is there some other way of removing the controller during run time and inserting it back in with full functionality that I'm not finding?

Thanks,
Pete

**Comment by Neuronix2** [comment]
Solved in my pull reqest

**Comment by zgmnkv** [comment]
Thanks @Neuronix2
