### ISSUE TITLE
How to grab the NOTIFICATION value

### ISSUE THREAD

**Issue by PeteDub** [zgmnkv/zwave4j#32]
I've noticed that the NotficationWatcher has a case for NOTIFICATION messages.  After some research, I've found that there is a

     aByte

value within the Notification object that is sent with this message, and that it seems to correlate with a code that is an extension of the NOTIFICATION message:

     Code_MsgComplete 	        Completed messages
     Code_Timeout 	            Messages that timeout will send a Notification with this code.
     Code_NoOperation 	        Report on NoOperation message sent completion
     Code_Awake 	            Report when a sleeping node wakes up
     Code_Sleep 	            Report when a node goes to sleep
     Code_Dead 	                Report when a node is presumed dead
     Code_Alive 	            Report when a node is revived

The order of these codes appear to correlate with the value of aByte and the status of the device with which the NOTIFICATION is concerning (this info was found at http://www.openzwave.com/dev/classOpenZWave_1_1Notification.html#ae1a158109af2e17f8a83101a50809ca3).

Is there a way to access the aByte value that I'm not seeing?  Using

     Manager.get().getValueAsXXXXX(notification.getValueId(), var);

with any value type doesn't seem to work.  Having this notification code would be very useful in my application.  Any suggestions?

Thanks,
Pete

(Sorry to send questions back to back like this.)

**Comment by Neuronix2** [comment]
See my pull request

**Comment by zgmnkv** [comment]
#30 merged, thanks @Neuronix2 !
