### ISSUE TITLE
Bad global or local ref passed to JNI

### ISSUE THREAD

**Issue by johnsirach** [zgmnkv/zwave4j#34]
I'm using this library in my project which uses a different class loader and with library loading in a separate kept alive thread. The above message appeared when debugging jni (because i did not got any notifications back). It looks like the wrong class loader was used as it could not find any class.

init.cpp has:
``` c++

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM * vm, void * pvt)
{
	jvm = vm;
	JNIEnv * env;
	if (jvm->GetEnv((void **) &env, JNI_VERSION_1_6))
	{
         return JNI_ERR; /* JNI version not supported */
    }

    jclass threadClass = env->FindClass("java/lang/Thread");
    classLoader = env->NewGlobalRef(env->CallObjectMethod(
            env->CallStaticObjectMethod(
                    threadClass,
                    env->GetStaticMethodID(threadClass, "currentThread", "()Ljava/lang/Thread;")
            ),
            env->GetMethodID(threadClass, "getContextClassLoader", "()Ljava/lang/ClassLoader;")
    ));

	return JNI_VERSION_1_6;
}
```
which returns the application class loader unless the used class loader is registered on the thread.

Possible solution is adding the next to NativeLibraryLoader.java:
``` java
Thread.currentThread().setContextClassLoader(ZWave4j.class.getClassLoader());
```
This makes sure the class loader which loads the library is used with the findclass.

**Comment by zgmnkv** [comment]
Hi @johnsirach,
Can you provide a minimal application that reproduces this error?

**Comment by johnsirach** [comment]
Will produce one in the next couple of days as i'm in quite a busy period.

To show short and simple:
structure
/myApp.jar (app.class, /folder/** not included in classpath)
/folder/module/module.jar (module.class)
/folder/module/libs/zwave4j.jar (zwave4j.class)

MyApp.jar contains CustomClassLoader which extends URLClassLoader and when instantiated adds the paths to module.jar and zwave4j.jar.

app.class instantiates module.class using the CustomClassLoader. The classpaths to the classes in module.jar and zwave4j.jar are only known in CustomClassLoader.

In my case the above process is done in a thread spawned when for example a zwave enabled usb dongle has been inserted (using libudev) or is found during usb devices discovery (also libudev) when my app starts.

This loading thread ends, so zwave4j is loaded in it's own dedicated thread which also calls the jni functions.

The issue rises when in the jni findclass is ran because as mentioned above "getContextClassLoader" returns the AppClassLoader which knows nothing about the zwave4j.class.

Changing : 
``` java
new Thread(() -> {
    NativeLibraryLoader.loadLibrary(ZWave4j.LIBRARY_NAME, ZWave4j.class);
    /*
    ......
    */
}).start();
```

To:
``` java
new Thread(() -> {
    Thread.currentThread().setContextClassLoader(ZWave4j.class.getClassLoader());
    NativeLibraryLoader.loadLibrary(ZWave4j.LIBRARY_NAME, ZWave4j.class);
    /*
    ......
    */
}).start();
```

Solved it because zwave4j.class is loaded with CustomClassLoader.

I hope i'm not too cryptic, which had more time to explain and provide a small app now.

P.S. I've read you do not have enough time to create builds. In a couple of weeks my jenkins setup will be extended with cross compiling and maybe extra build nodes. Need to take a closer look to this but maybe i can help by providing a build environment.

**Comment by zgmnkv** [comment]
Seems that it's the same as #36
