### ISSUE TITLE
I can't find the native_libs inside the built jar

### ISSUE THREAD

**Issue by scarlet033** [zgmnkv/zwave4j#35]
Hi ,
I tried to build the zwave4j jar file by following the steps explained in git-hub, but the built jar doesn't contains the native_libs directory. (contains just classes and manifest file)
my host config : Ubuntu 14.04 amd64.
Thanks

**Comment by zgmnkv** [comment]
Hi, can you please attach build log?

**Comment by scarlet033** [comment]
Hi,
From console after executing "gradlew build" command 
:configZip
:compileJava
:processResources UP-TO-DATE
:classes
:copyNativeLibs UP-TO-DATE
:jar
:javadoc
:javadocJar
:sourcesJar
:signArchives SKIPPED
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 15.343 secs

**Comment by zgmnkv** [comment]
Seems that gradle didn't recognize a compiler toolchain. Do you have gcc installed? Is it on your PATH?

**Comment by scarlet033** [comment]
After installing this packages gcc, g++, gcc-4.8-multilib, g++-4.8-multilib
the built jar contains native_libs directory, but the jar doesn't work well, 
I test the Main class and I got this error
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/native-lib-5990416980919581241.tmp: /tmp/native-lib-5990416980919581241.tmp: undefined symbol: ozw_version_string
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.zwave4j.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at org.zwave4j.Main.main(Main.java:17)

----------
Log gradlew build 
:configZip
:compileJava
:processResources UP-TO-DATE
:classes
:mainCExtractHeaders
:compileLinux_amd64MainSharedLibraryMainC
:generateNativeHeaders
:generateOzwVersionCpp
:mainCppExtractHeaders
:compileLinux_amd64MainSharedLibraryMainCpp
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2(JNIEnv*, jobject, jlong, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2141:130: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command)));
                                                                                                                                  ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2(JNIEnv*, jobject, jlong, jobject, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2156:158: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair));
                                                                                                                                                              ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2(JNIEnv*, jobject, jlong, jobject, jobject, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2171:158: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair));
                                                                                                                                                              ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2Z(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2186:178: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower)));
                                                                                                                                                                                  ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2ZS(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean, jshort)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2201:196: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower), getUint8(nodeId)));
                                                                                                                                                                                                    ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2ZSS(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean, jshort, jshort)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2216:211: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower), getUint8(nodeId), getUint8(arg)));
                                                                                                                                                                                                                   ^
:linkLinux_amd64MainSharedLibrary
:compileLinux_x86MainSharedLibraryMainC
:compileLinux_x86MainSharedLibraryMainCpp
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2(JNIEnv*, jobject, jlong, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2141:130: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command)));
                                                                                                                                  ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2(JNIEnv*, jobject, jlong, jobject, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2156:158: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair));
                                                                                                                                                              ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2(JNIEnv*, jobject, jlong, jobject, jobject, jobject)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2171:158: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair));
                                                                                                                                                              ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2Z(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2186:178: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower)));
                                                                                                                                                                                  ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2ZS(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean, jshort)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2201:196: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower), getUint8(nodeId)));
                                                                                                                                                                                                    ^
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp: In function ‘jboolean Java_org_zwave4j_Manager_beginControllerCommand__JLorg_zwave4j_ControllerCommand_2Lorg_zwave4j_ControllerCallback_2Ljava_lang_Object_2ZSS(JNIEnv*, jobject, jlong, jobject, jobject, jobject, jboolean, jshort, jshort)’:
/home/marou/Documents/work/zwave4j/zwave4j-master_4/src/main/cpp/org_zwave4j_Manager.cpp:2216:211: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated (declared at /home/marou/Documents/work/zwave4j/open-zwave-master/cpp/src/Manager.h:1728) [-Wdeprecated-declarations]
     return getJboolean(OpenZWave::Manager::Get()->BeginControllerCommand(getUint32(homeId), getOzwControllerCommand(env, command), onControllerCallback, pair, getBool(highPower), getUint8(nodeId), getUint8(arg)));
                                                                                                                                                                                                                   ^
:linkLinux_x86MainSharedLibrary
:copyNativeLibs
:jar
:javadoc
:javadocJar
:sourcesJar
:signArchives SKIPPED
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

**Comment by zgmnkv** [comment]
Sorry for late reply, currently zwave4j doesn't generate vers.cpp itself, you need to generate it with openzwave makefile. Go to openzwave directory and execute 'make', rebuild zwave4j after that.
