### ISSUE TITLE
Sonatype snapshot repo not available

### ISSUE THREAD

**Issue by mcicolella** [zgmnkv/zwave4j#37]
Hi, as reported in your README file, I'm trying to include the last snapshot but the repo is unavailable.
Any idea or tip?

Thanks

**Comment by zgmnkv** [comment]
Hi, I'm not able to build snapshots for all platforms after each commit currently, so latest available version is release in maven central.

**Comment by mcicolella** [comment]
I have a JVM crash and I'd like to try https://github.com/zgmnkv/zwave4j/pull/30 to verify if it solves the issue. A CI system could help you to automate the building process.

**Comment by zgmnkv** [comment]
You can try to build it yourself. Travis CI is on my list, but it supports only linux and osx. Do you know any other free CI for multi-platform build?

**Comment by mcicolella** [comment]
We use Teamcity for our project freedomotic.com. 
Take a look at http://teamcity.codebetter.com/project.html?projectId=Freedomotic (login as guest).
Also there is another good solution https://codeship.com/

**Comment by zgmnkv** [comment]
I have uploded a snapshot with linux 64 bit binary only https://oss.sonatype.org/content/repositories/snapshots/com/github/zgmnkv/zwave4j/

**Comment by zgmnkv** [comment]
Snapshot with all platforms is uploaded
